[package]
name = "fsutils"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
mvsum = { path = "../mvsum" }
dss = { path = "../dss" }
ddup = { path = "../ddup" }
ssim = { path = "../ssim" }
fix-ext = { path = "../fix-ext" }
towebp = { path = "../towebp" }
